<style type="text/css">
          #map {
            
          }
          #result {
		  	float:left;
            width: 1px;
            height: 80%;
            margin: auto;
            border: 4px solid #dddddd;
            background: #ffffff;
            overflow: auto;
            z-index: 2;
        }
        </style>
<div class="container" style="margin-top:10px;">
	<div class="jumbotron">
		<p>...</p>
		<h3>Exam I : X, Y, 5, 9, 15, 23, Z  - Please create a new function for finding X, Y, Z value</h3>
		<?php foreach ($this->dataExamI as $value) { echo $value.","; }?>
		
		<h3>If A = 21, A + B = 23, A + C = -21 - Please create a new function for finding B and C value</h3>
		<?php echo "B = ".$this->dataExamII[0]." and C = ".$this->dataExamII[1];?>

		<h3>Please use “Google API” for finding the best way to go to Central World from SCG Bangsue</h3>
		<div style="width:800px;height:400px;">
			<div id="map" style="height: 100%;width:500px;float:left;"></div>
			<div id="result" style="float:left;width: 1px;height: 80%;margin: auto;border: 4px solid #dddddd;background: #ffffff;overflow: auto;z-index: 2;"></div>
		</div>
		<div style="color:red;font-size:0.85em;margin:10px 0 0 0;"> **API Google map directionในตอนที่เขียนโปรแกรมอยู่นี้ไม่สามารถใช้ฟรีได้ จึงได้เปลี่ยนเป็นตัวที่มีคุณสมบัติใกล้เคียงกันและไม่เสียค่าใช้จ่ายแทน เป็นของ longdo.com </div>
	</div>
</div>
